// File generated by FlutterFire CLI or custom template.
// Replace these with your actual Firebase project credentials from Firebase Console.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String _projectId = String.fromEnvironment(
    'FIREBASE_PROJECT_ID',
    defaultValue: 'restaurant-app-paragon',
  );
  static const String _senderId = String.fromEnvironment(
    'FIREBASE_MESSAGING_SENDER_ID',
    defaultValue: '1234567890',
  );
  static const String _storageBucket = String.fromEnvironment(
    'FIREBASE_STORAGE_BUCKET',
    defaultValue: 'restaurant-app-paragon.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY',
        defaultValue: 'AIzaSyDemoWebApiKeyPlaceholder12345678'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID',
        defaultValue: '1:1234567890:web:abcdef123456'),
    messagingSenderId: _senderId,
    projectId: _projectId,
    authDomain: String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN',
        defaultValue: 'restaurant-app-paragon.firebaseapp.com'),
    storageBucket: _storageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY',
        defaultValue: 'AIzaSyDemoAndroidApiKeyPlaceholder123456'),
    appId: String.fromEnvironment('FIREBASE_ANDROID_APP_ID',
        defaultValue: '1:1234567890:android:abcdef123456'),
    messagingSenderId: _senderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY',
        defaultValue: 'AIzaSyDemoIosApiKeyPlaceholder12345678'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID',
        defaultValue: '1:1234567890:ios:abcdef123456'),
    messagingSenderId: _senderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID',
        defaultValue: 'com.example.restaurantApp'),
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY',
        defaultValue: 'AIzaSyDemoMacosApiKeyPlaceholder123456'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID',
        defaultValue: '1:1234567890:ios:abcdef123456'),
    messagingSenderId: _senderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID',
        defaultValue: 'com.example.restaurantApp'),
  );
}

